alias gs='git status '
alias gp='git push'
alias gps='git push'
alias gpl='git pull'
alias gpu='git pull'
alias ga='git add '
alias gb='git branch '
alias gca='git commit -a -v '
alias gc='git commit'
alias gd='git diff'
#alias gl='git log '
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gll="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit -p"
alias gco='git checkout '
alias gcl='git clone '
